---
- name: Install and Run Docker Container
  hosts: all
  become: yes
  tasks: 
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    - name: Run Docker container
      command: docker run -d -p 8084:8081 saigowtham2605/financeme1:1.0
